# Generated by Django 5.0 on 2024-03-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiljeanApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=10000)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.AlterModelTable(
            name='quotes',
            table='quote',
        ),
        migrations.AlterModelTable(
            name='slider',
            table='slider',
        ),
    ]
