# Generated by Django 5.0 on 2024-03-10 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiljeanApp', '0004_subscription'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subscription',
            table='subscription',
        ),
    ]
