# Generated by Django 5.0 on 2024-03-12 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiljeanApp', '0007_music'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='music',
            table='music',
        ),
    ]
