# Generated by Django 5.0 on 2024-03-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiljeanApp', '0009_album_music_album'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='album',
        ),
    ]
