# Generated by Django 5.0 on 2024-03-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiljeanApp', '0010_alter_album_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.IntegerField(default=0),
        ),
    ]
