# Generated by Django 5.0 on 2024-03-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiljeanApp', '0012_album_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=10000)),
                ('image', models.ImageField(upload_to='music_files')),
                ('publish_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
