# Generated by Django 5.0 on 2024-03-21 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiljeanApp', '0014_other_peoples_music'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='blog',
        ),
        migrations.AlterModelTable(
            name='other_peoples_music',
            table='other_music',
        ),
    ]
