# Generated by Django 5.0 on 2024-03-21 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiljeanApp', '0015_alter_blog_table_alter_other_peoples_music_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='other_peoples_music',
            old_name='music',
            new_name='file',
        ),
    ]
