# Generated by Django 5.0 on 2024-03-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiljeanApp', '0016_rename_music_other_peoples_music_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='publish_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
