# Generated by Django 5.0 on 2024-03-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiljeanApp', '0017_music_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='publish_date',
            field=models.DateField(),
        ),
    ]
