# Generated by Django 5.0 on 2024-03-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiljeanApp', '0019_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='other_peoples_music',
            name='photo',
            field=models.ImageField(null=True, upload_to='image_file'),
        ),
    ]
