# Generated by Django 5.0 on 2024-03-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiljeanApp', '0020_other_peoples_music_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WiljeanGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='image_file')),
            ],
        ),
    ]
