# Generated by Django 5.0 on 2024-03-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiljeanApp', '0022_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
