# Generated by Django 5.0 on 2024-03-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiljeanApp', '0023_events_author_events_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
