# Generated by Django 5.0 on 2024-03-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiljeanApp', '0024_events_address_events_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='body',
            field=models.TextField(max_length=1500),
        ),
    ]
