# Generated by Django 5.0 on 2024-04-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiljeanApp', '0026_music_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='website',
        ),
    ]
