# Generated by Django 5.0 on 2024-04-08 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiljeanApp', '0027_remove_contact_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='replyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(max_length=1000)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiljeanApp.contact')),
            ],
        ),
    ]
