# Generated by Django 5.0 on 2024-04-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiljeanApp', '0028_replycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='replycontact',
            name='reply',
            field=models.BooleanField(default=False),
        ),
    ]
