# Generated by Django 5.0 on 2024-04-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiljeanApp', '0031_alter_gallery_options_alter_wiljeangallery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
