# Generated by Django 5.0 on 2024-04-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiljeanApp', '0032_alter_blogcomment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
