# Generated by Django 5.0 on 2024-04-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiljeanApp', '0034_alter_blog_content_alter_blog_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='music_files', verbose_name='content'),
        ),
    ]
