# Generated by Django 5.0 on 2024-04-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiljeanApp', '0038_remove_blog_publish_date_blogtranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtranslation',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='blog',
            name='publish_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
