# Generated by Django 5.0 on 2024-04-22 14:12

import django.db.models.deletion
import parler.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiljeanApp', '0039_remove_blogtranslation_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='wiljeanApp.blog'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='body',
            field=models.CharField(max_length=500),
        ),
    ]
